In [1]:
import pandas as pd
import numpy as np

In [17]:
census = pd.read_csv('census.csv', index = 'State')

TypeError: parser_f() got an unexpected keyword argument 'index'

In [16]:
census

,City,State,Population
0,New York city,New York,8537673
1,Los Angeles city,California,3976322
2,Chicago city,Illinois,2704958
3,Houston city,Texas,2303482
4,Phoenix city,Arizona,1615017
5,Philadelphia city,Pennsylvania,1567872
6,San Antonio city,Texas,1492510
7,San Diego city,California,1406630
8,Dallas city,Texas,1317929
9,San Jose city,California,1025350
10,Austin city,Texas,947890
11,Jacksonville city,Florida,880619
12,San Francisco city,California,870887
13,Columbus city,Ohio,860090
14,Indianapolis city (balance),Indiana,855164
15,Fort Worth city,Texas,854113
16,Charlotte city,North Carolina,842051
17,Seattle city,Washington,704352
18,Denver city,Colorado,693060
19,El Paso city,Texas,683080
20,Washington city,District of Columbia,681170
21,Boston city,Massachusetts,673184
22,Detroit city,Michigan,672795
23,Nashville-Davidson metropolitan government (ba...,Tennessee,660388
24,Memphis city,Tennessee,652717
25,Portland city,Oregon,639863
26,Oklahoma City city,Oklahoma,638367
27,Las Vegas city,Nevada,632912
28,Louisville/Jefferson County metro government (...,Kentucky,616261
29,Baltimore city,Maryland,614664
...,...,...,...
19480,Artas town,South Dakota,8
19481,Wetonka town,South Dakota,8
19482,Clayton city,Idaho,7
19483,South Park View city,Kentucky,7
19484,Fontana Dam town,North Carolina,7
19485,Bergen city,North Dakota,7
19486,Grano city,North Dakota,7
19487,Three Creeks village,Missouri,6
19488,Anoka village,Nebraska,6
19489,Lambert town,Oklahoma,6
19490,Lowry town,South Dakota,6
19491,Freeport city,Kansas,5
19492,Funkley city,Minnesota,5
19493,Cave town,Missouri,5
19494,Tavistock borough,New Jersey,5
19495,Verdon town,South Dakota,5
19496,Thurmond town,West Virginia,5
19497,Ruso city,North Dakota,4
19498,Hoot Owl town,Oklahoma,4
19499,Lily town,South Dakota,4
19500,Lost Springs town,Wyoming,4
19501,Warm River city,Idaho,3
19502,Hillsview town,South Dakota,3
19503,White Rock town,South Dakota,3
19504,Gross village,Nebraska,2
19505,Lotsee town,Oklahoma,2
19506,Monowi village,Nebraska,1
19507,Goss town,Missouri,0
19508,Carlton Landing town,Oklahoma,0
19509,Buffalo Chip town,South Dakota,0