In [1]:
# Dependencies Libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests as req
import json
import ipywidgets as widgets
from IPython.display import display, HTML
from ipywidgets import interactive, Layout, Textarea, Dropdown, Label
HTML('<style> .widget-hbox .widget-label { max-width:350ex; text-align:left} </style>')

In [2]:
# Population Catagory Options in a list 
population_catagory = ['>=100000','>=250000','>=500000','>=1000000']

labor_force_catagory = ['Management','Business and Financial Operations','Computer and Mathematical',
                        'Architecture and Engineering','Life, Physical, and Social Science',
                        'Community and Social Service','Legal','Education, Training, and Library',
                        'Arts, Design, Entertainment, Sports, and Media','Healthcare Practitioners and Technical',
                        'Healthcare Support','Protective Service','Food Preparation and Serving Related',
                        'Building and Grounds Cleaning and Maintenance','Personal Care and Service',
                        'Sales and Related','Office and Administrative Support','Farming, Fishing, and Forestry',
                        'Construction and Extraction','Installation, Maintenance, and Repair','Production',
                        'Transportation and Material Moving']

In [3]:
form_item_layout = Layout(
    display='flex',
    #flex_flow='row',
    justify_content='space-between',
    flex_flow='column',
    border='solid 2px',
    align_items='stretch',
    width='70%'
)

In [4]:
census = pd.read_csv('Census.csv', encoding="ISO-8859-1")
census.head()

# Move Population to just left of Population Score

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0

In [5]:
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 10 columns):
City                    303 non-null object
Population              303 non-null int64
County                  303 non-null object
State                   303 non-null object
FullState               303 non-null object
MSA                     303 non-null object
Population Score        303 non-null float64
Closest Airport         303 non-null object
Proximity to Airport    303 non-null int64
Airport Score           303 non-null float64
dtypes: float64(2), int64(2), object(6)
memory usage: 23.8+ KB

In [6]:
# Define Population function to choose the population catagory as part of the Selection Widgets
def f(Population):
    if Population =='>=100000':
        Population = 100000
    elif Population == '>=250000':
        Population = 250000
    elif Population == '>=500000':
        Population = 500000
    else:
        Population = 1000000
    return Population

# Create Lists using interactive
Population = interactive(f,Population=population_catagory)
                         #,layout=form_item_layout)

# You can also view this in a notebook without using display.
display(Population)

In [7]:
# This is to show the user selection value for the Minimum Population 
Minimum_population = Population.result
Minimum_population

1000000

In [10]:
# Define Labor force Catagory function to choose the Labor force Catagory as part of the Selection Widgets
def f(Primary):
    return Primary
# Create Lists using interactive
primary = interactive(f,Primary=labor_force_catagory,layout=form_item_layout)

# You can also view this in a notebook without using display.
display(primary)

In [11]:
primary.result

'Computer and Mathematical'

In [12]:
Secondary_labor_force_catagory = [x for x in labor_force_catagory if x != primary.result]

In [13]:
# Define Labor force Catagory function to choose the Labor force Catagory as part of the Selection Widgets
def f(Secondary):
    return Secondary
# Create Lists using interactive
secondary = interactive(f,Secondary=Secondary_labor_force_catagory,layout=form_item_layout)

# You can also view this in a notebook without using display.
display(secondary)

In [14]:
secondary.result

'Business and Financial Operations'

In [15]:
optional_labor_force_catagory = [x for x in Secondary_labor_force_catagory if x != secondary.result]

In [16]:
optional = widgets.SelectMultiple(
    options=optional_labor_force_catagory,
    #value=['Oranges'],
    layout=form_item_layout,
    rows=20,
    description='Optional',
    disabled=False
)
display(optional)

In [17]:
optional.value

('Management',)

In [18]:
style = {'description_width': 'initial'}
Pop_weight = widgets.IntSlider(
    value=0,
    min=1,
    max=10,
    step=1,
    description='Population Weight',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
    style=style
)

display(Pop_weight)

TraitError: The 'style' trait of an IntSlider instance must be a SliderStyle, but a value of class 'dict' (i.e. {'description_width': 'initial'}) was specified.

In [17]:
Pop_weight.value

1

In [18]:
style = {'description_width': 'initial'}
Labor_weight = widgets.IntSlider(
    value=0,
    min=1,
    max=10,
    step=1,
    description='Labor Force Weight',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
    style=style
)

display(Labor_weight)

IntSlider(value=1, continuous_update=False, description='Labor Force Weight', max=10, min=1, style=SliderStyle(description_width='initial'))

In [19]:
Labor_weight.value

1

In [20]:
style = {'description_width': 'initial'}
Airport_weight = widgets.IntSlider(
    value=0,
    min=1,
    max=10,
    step=1,
    description='Proximity to Airport Weight',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
    style=style
)

display(Airport_weight)

IntSlider(value=1, continuous_update=False, description='Proximity to Airport Weight', max=10, min=1, style=SliderStyle(description_width='initial'))

In [21]:
Airport_weight.value

1

In [22]:
census = census[(census["Population"] >= Minimum_population)]
census["Primary Occupation"] = ""
census["Secondary Occupation"] = ""
census["Additional Occupations"] = ""
census.head()

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score,Primary Occupation,Secondary Occupation,Additional Occupations
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4,,,
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0,,,
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8,,,
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8,,,
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0,,,

In [23]:
laborforce = pd.read_csv('LaborForce.csv')
laborforce.head()

,AREA_NAME,OCC_TITLE,TOT_EMP,JOBS_1000,LOC QUOTIENT,Score
0,"Abilene, TX",Management,"2,030",31.741,0.63,3.15
1,"Abilene, TX",Business and Financial Operations,"2,230",34.804,0.67,3.35
2,"Abilene, TX",Computer and Mathematical,920,14.402,0.49,2.45
3,"Abilene, TX",Architecture and Engineering,710,11.068,0.62,3.10
4,"Abilene, TX","Life, Physical, and Social Science",380,5.901,0.72,3.60

In [24]:
Primary = primary.result

for index2, row in census.iterrows():
    MSA = row["MSA"]
    Scores = []
    
    for index, row in laborforce.iterrows():
        if row["AREA_NAME"] == MSA and row["OCC_TITLE"] == Primary:
            Scores.append(row["Score"])
            #print("Got Primary Score")
            #print(row["Score"])
    
    #print(Scores)
    census.set_value(index2, "Primary Occupation", round(Scores[0],1))
    
census.head()

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score,Primary Occupation,Secondary Occupation,Additional Occupations
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4,5.6,,
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0,5.4,,
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8,7.5,,
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8,4.3,,
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0,5.7,,

In [25]:
Secondary = secondary.result

for index4, row in census.iterrows():
    MSA = row["MSA"]
    Scores = []
    
    for index, row in laborforce.iterrows():
        if row["AREA_NAME"] == MSA and row["OCC_TITLE"] == Secondary:
            Scores.append(row["Score"])
            #print("Got Secondary Score")
            #print(row["Score"])

    #print(Scores)
    census.set_value(index4, "Secondary Occupation", round(Scores[0],1))
    
census.head()

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score,Primary Occupation,Secondary Occupation,Additional Occupations
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4,5.6,6.5,
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0,5.4,5.5,
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8,7.5,5.9,
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8,4.3,5.1,
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0,5.7,5.4,

In [26]:
Optional = list(optional.value)
total_optional = len(Optional)
if total_optional != 0:
    for index6, row in census.iterrows():
        MSA = row["MSA"]
        optional_value = 0
        avg_optional = 0

        for index, row in laborforce.iterrows():
            for occupation in Optional:
                if row["AREA_NAME"] == MSA and row["OCC_TITLE"] == occupation:
                    optional_value += row["Score"]
                    #print("Got Additional Score", occupation)

        avg_optional = optional_value / total_optional
        #print(avg_optional)

        census.set_value(index6, "Additional Occupations", round(avg_optional,1))
    
census.head()

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score,Primary Occupation,Secondary Occupation,Additional Occupations
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4,5.6,6.5,
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0,5.4,5.5,
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8,7.5,5.9,
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8,4.3,5.1,
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0,5.7,5.4,

In [27]:
if total_optional != 0:
    census["Labor Force Score"] = (5 * census["Primary Occupation"] + 3 * census["Secondary Occupation"] + 2 * census["Additional Occupations"]) / 10
else:
    census["Labor Force Score"] = (5 * census["Primary Occupation"] + 3 * census["Secondary Occupation"])

census.head()

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score,Primary Occupation,Secondary Occupation,Additional Occupations,Labor Force Score
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4,5.6,6.5,,47.5
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0,5.4,5.5,,43.5
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8,7.5,5.9,,55.2
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8,4.3,5.1,,36.8
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0,5.7,5.4,,44.7

In [28]:
census["City, State"] = (census["City"] + ", " + census["FullState"])
#census.head()

In [35]:
census["Overall Score"] = (Pop_weight.value * census["Population Score"] + Labor_weight.value * census["Labor Force Score"] + Airport_weight.value * census["Airport Score"]) / (Pop_weight.value + Labor_weight.value + Airport_weight.value) * 10
census.head()

,City,Population,County,State,FullState,MSA,Population Score,Closest Airport,Proximity to Airport,Airport Score,Primary Occupation,Secondary Occupation,Additional Occupations,Labor Force Score,"City, State",Overall Score
0,New York,8537673,Bronx County,NY,New York,"New York-Jersey City-White Plains, NY-NJ Metro...",10.0,Newark Liberty International Airport,28,6.4,5.6,6.5,,47.5,"New York, New York",213
1,Los Angeles,3976322,Los Angeles County,CA,California,"Los Angeles-Long Beach-Glendale, CA Metropolit...",10.0,Los Angeles International Airport,25,7.0,5.4,5.5,,43.5,"Los Angeles, California",201.667
2,Chicago,2704958,Cook County,IL,Illinois,"Chicago-Naperville-Arlington Heights, IL Metro...",10.0,O'Hare International Airport,31,5.8,7.5,5.9,,55.2,"Chicago, Illinois",236.667
3,Houston,2303482,Harris County,TX,Texas,"Houston-The Woodlands-Sugar Land, TX",10.0,George Bush Intercontinental Airport,21,7.8,4.3,5.1,,36.8,"Houston, Texas",182
4,Phoenix,1615017,Maricopa County,AZ,Arizona,"Phoenix-Mesa-Scottsdale, AZ",10.0,Phoenix Sky Harbor International Airport,9,10.0,5.7,5.4,,44.7,"Phoenix, Arizona",215.667

In [30]:
result = census[["City, State", "Population Score", "Labor Force Score", "Airport Score", "Overall Score"]]
result = result.sort_values('Overall Score', ascending=False)
result.index = np.arange(1, len(result) + 1)
result.head(10)

,"City, State",Population Score,Labor Force Score,Airport Score,Overall Score
1,"San Francisco, California",8.5,67.4,6.8,275.667
2,"Boston, Massachusetts",6.6,65.5,10.0,273.667
3,"Oakland, California",4.1,67.4,9.2,269
4,"Hayward, California",1.6,67.4,9.0,260
5,"Washington, District of Columbia",6.6,68.2,2.8,258.667
6,"Fremont, California",2.3,67.4,7.0,255.667
7,"Berkeley, California",1.2,67.4,7.6,254
8,"Cambridge, Massachusetts",1.1,65.5,8.8,251.333
9,"Richmond, California",1.1,67.4,6.8,251
10,"San Jose, California",10.0,61.5,3.6,250.333

In [31]:
# Add Plots